Parse text
CTN-0094/DOPE pull request #9
Opened 2021-02-25 22:52 UTC by labouz

needs tests

2021-03-08 22:57 UTC, labouz commented
@nathan-castor this function needs a test pls

2021-03-09 00:53 UTC, nathan-castor commented
@labouz 
Looks like there are some conflicts with this code now, sorry I would've done this last week if I could have.

2021-03-09 21:56 UTC, nathan-castor requested changes
Woohoo!

2021-03-09 21:56 UTC, nathan-castor commented on R/parse.R
> +
Let's remove the commented code that's not serving a purpose

2021-03-09 21:56 UTC, nathan-castor commented on R/parse.R
> +#' parse(drug_df)
Incorrect argument name (drug_vec)

2021-03-09 21:56 UTC, nathan-castor commented on R/parse.R
> +  word <- drug <- for_token <- stop_words <- NULL
we don't need stop_words set to NULL here

2021-03-09 21:56 UTC, nathan-castor commented on R/parse.R
> +#'   free text field given a file path specified by the user.
edit description: we don't take a file path anymore

2021-03-09 21:56 UTC, nathan-castor commented on R/parse.R
> +  drugCol <- as.name(names(drugs))
unnecessary to create this variable because you are piping the df into the function on line 67

2021-03-15 17:49 UTC, nathan-castor requested changes
just two lines of commented code

2021-03-15 17:49 UTC, nathan-castor commented on R/parse.R
> +  # drugs <- get_col()
unneeded comments (commented code)

2021-03-15 17:49 UTC, nathan-castor commented on R/parse.R
> +  # drugCol <- as.name(names(drugs))
unneeded comments (commented code)

2021-03-15 18:03 UTC, nathan-castor approved these changes

2021-03-16 13:04 UTC, merged